// End-to-end acceptance gate. Run on a Chromium runner with WebGL support.
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
const base = process.env.BASE_URL || 'http://127.0.0.1:8000/';
const inspectURL = new URL(base);inspectURL.searchParams.set('inspect','1');
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads:true });
const page = await context.newPage();page.setDefaultTimeout(60000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('test-results',{recursive:true});
try {
  await page.goto(inspectURL.href,{waitUntil:'load'});
  await page.locator('#loading').waitFor({state:'hidden',timeout:60000});
  assert.equal(await page.locator('#fatal').isVisible(),false,'Renderer must initialize');
  await page.waitForFunction(()=>window.BYUR_POSTERS?.brezhnev?.naturalWidth===768&&window.BYUR_POSTERS?.plan?.naturalHeight===1024);
  await page.screenshot({path:'test-results/01-room.png'});
  const idleBefore=await page.evaluate(()=>window.BYUR_INSPECT.snapshot().frames);await page.waitForTimeout(800);const idleAfter=await page.evaluate(()=>window.BYUR_INSPECT.snapshot().frames);assert(idleAfter-idleBefore<=2,'Static room must not render continuously');
  await page.locator('#deskView').click();
  await page.waitForFunction(()=>window.BYUR_INSPECT.viewReady());
  await page.screenshot({path:'test-results/02-desk.png'});
  await page.locator('#runDoc').click();
  await page.waitForFunction(()=>document.querySelector('#hint').textContent.startsWith('ЄЯЯOЯ'));
  const sample='COMRADE DOCUMENT\nThis document requests certification of its own existence.\n';
  await page.locator('#file').setInputFiles({name:'FORM-27B.txt',mimeType:'text/plain',buffer:Buffer.from(sample)});
  await page.locator('#sound').click();
  await page.waitForFunction(()=>window.MinistryAudio.state().decoded.length===10,{},{timeout:30000});
  await page.locator('#music').click();await page.waitForFunction(()=>window.MinistryAudio.state().musicOn&&window.MinistryAudio.state().context==='running');
  await page.locator('#runDoc').click();
  assert.equal(await page.locator('#loadDoc').isDisabled(),true,'No replacing file mid-cycle');
  await page.waitForFunction(()=>document.querySelector('#hint').textContent.startsWith('APPЯOVЄD'),{},{timeout:90000});
  const mechanics=await page.evaluate(()=>window.BYUR_INSPECT.snapshot());assert(mechanics.recoilPeak>0,'Stamp has cabinet recoil');assert(mechanics.paperBend>.05,'Paper bends around rollers');assert.equal(mechanics.issued,1);assert.equal(mechanics.archiveSheets,1);assert.equal(mechanics.counterDisplay,1);
  console.log('ОТК: cycle, weight, issued tray and spatial audio passed');
  await page.screenshot({path:'test-results/03-completed.png'});
  await page.locator('#sideView').click();await page.waitForFunction(()=>window.BYUR_INSPECT.viewReady());
  await page.screenshot({path:'test-results/07-side.png'});
  await page.locator('#sound').click();assert.equal(await page.evaluate(()=>window.MinistryAudio.state().effectsOn),false);assert.equal(await page.evaluate(()=>window.MinistryAudio.state().musicOn),true);
  await page.locator('#volume').press('Home');assert.equal(await page.evaluate(()=>window.MinistryAudio.state().volume),0);await page.locator('#volume').press('End');
  await page.locator('#music').click();assert.equal(await page.evaluate(()=>window.MinistryAudio.state().musicOn),false);
  await page.locator('#receipt').click();
  await page.screenshot({path:'test-results/04-certificate.png'});
  const downloaded=page.waitForEvent('download');await page.locator('#downloadReceipt').click();
  const download=await downloaded;await download.saveAs('test-results/certificate.png');
  const png=await readFile('test-results/certificate.png');assert.equal(png.subarray(1,4).toString(),'PNG');
  await page.locator('#closeReceipt').click();
  await page.locator('#file').setInputFiles({name:'SECOND.txt',mimeType:'text/plain',buffer:Buffer.from('Second document')});
  assert.equal(await page.locator('#receipt').isDisabled(),true,'New file clears previous certificate');
  await page.locator('#resetDoc').click();assert.equal(await page.locator('#file').inputValue(),'');
  await page.reload();await page.locator('#loading').waitFor({state:'hidden',timeout:60000});
  assert.equal(await page.locator('#fatal').isVisible(),false);
  const sceneInfo=await page.evaluate(()=>window.BYUR_INSPECT.snapshot());
  assert.equal(sceneInfo.issued,1,'Issued counter survives reload');assert.equal(sceneInfo.archiveSheets,1,'Receiving tray restores');assert(sceneInfo.safe);assert(sceneInfo.machine[0]>1.1&&sceneInfo.machine[0]<1.5);
  const blocked=await page.evaluate(()=>[[0,-1.5],[-4.4,-5.5],[-3.6,-3.7],[4,-5.2],[3.94,-4.3],[6,0]].map(([x,z])=>window.BYUR_INSPECT.canStand(x,z)));assert.deepEqual(blocked,[false,false,false,false,false,false]);
  await page.locator('#deskView').click();await page.waitForFunction(()=>window.BYUR_INSPECT.viewReady());
  await page.locator('#app canvas').click({position:{x:30,y:600}});
  await page.keyboard.down('w');await page.waitForFunction(()=>window.BYUR_INSPECT.snapshot().camera[2]<-.62,{},{timeout:30000});await page.keyboard.up('w');
  await page.keyboard.down('w');await page.waitForTimeout(350);await page.keyboard.up('w');
  console.log('ОТК: movement reached workbench');
  const stopped=await page.evaluate(()=>window.BYUR_INSPECT.snapshot());assert(stopped.safe&&stopped.camera[2]>-.69,'Player is blocked by workbench');
  await page.locator('#roomView').click();await page.waitForFunction(()=>window.BYUR_INSPECT.viewReady());
  const state=await page.evaluate(async()=>({cache:await caches.keys(),worker:!!navigator.serviceWorker.controller,manifest:await fetch('./manifest.webmanifest').then(r=>r.json())}));
  assert(state.worker);assert(state.cache.includes('byurokyadt-v10-0'));assert.equal(state.manifest.display,'standalone');
  await context.setOffline(true);await page.reload();await page.locator('#loading').waitFor({state:'hidden',timeout:60000});
  assert.equal(await page.locator('#fatal').isVisible(),false,'Offline shell renders');
  await page.screenshot({path:'test-results/05-offline.png'});
  await page.locator('#sound').click();await page.waitForFunction(()=>window.MinistryAudio.state().decoded.length===10,{},{timeout:30000});
  await page.locator('#sound').click();assert.equal(await page.locator('#sound').getAttribute('aria-pressed'),'false');
  await context.setOffline(false);
  await page.mouse.move(700,500);await page.mouse.down();await page.mouse.move(960,500,{steps:8});await page.mouse.up();await page.screenshot({path:'test-results/09-door.png'});
  await page.locator('#roomView').click();await page.waitForFunction(()=>window.BYUR_INSPECT.viewReady());
  await page.mouse.move(700,500);await page.mouse.down();await page.mouse.move(491,500,{steps:8});await page.mouse.up();await page.screenshot({path:'test-results/10-window.png'});
  await page.locator('#roomView').click();await page.waitForFunction(()=>window.BYUR_INSPECT.viewReady());
  await page.setViewportSize({width:1100,height:700});await page.locator('#deskView').click();await page.waitForFunction(()=>window.BYUR_INSPECT.viewReady());await page.screenshot({path:'test-results/06-chromebook.png'});
  await page.setViewportSize({width:390,height:844});await page.locator('#roomView').click();await page.waitForFunction(()=>window.BYUR_INSPECT.viewReady());await page.screenshot({path:'test-results/08-mobile.png'});
  assert.equal(await page.locator('#runDoc').isVisible(),true);
  assert.deepEqual(errors,[]);
  await writeFile('test-results/result.json',JSON.stringify({passed:true,base,checks:['poster decode','WebGL scene','document selection','mechanical cycle','PNG certificate','reset','cached reload','offline reload','audio decode and controls','offline audio','cabinet dimensions','furniture collision','walking collision','narrow viewport','idle rendering','mechanism weight','bending paper','persistent physical counter and tray'],state,sceneInfo},null,2));
  console.log('ОТК: all acceptance checks passed.');
} catch(e) {
  await page.screenshot({path:'test-results/failure.png'}).catch(()=>{});
  await writeFile('test-results/failure.json',JSON.stringify({error:String(e),errors,hint:await page.locator('#hint').textContent().catch(()=>null),snapshot:await page.evaluate(()=>window.BYUR_INSPECT?.snapshot()).catch(()=>null)},null,2));
  console.error('ОТК ОШИБКА',e);throw e;
} finally { await browser.close(); }
